// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: protos/eventstore.proto

package eventstore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event represents a Nostr event
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // 32-byte SHA-256 hash
	Pubkey        []byte                 `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`                         // 32-byte Ed25519 public key
	CreatedAt     uint32                 `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // UNIX timestamp
	Kind          uint32                 `protobuf:"varint,4,opt,name=kind,proto3" json:"kind,omitempty"`                            // Event type (uint16 in Go)
	Tags          []*Tag                 `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`                             // Event tags
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                       // Event content
	Sig           []byte                 `protobuf:"bytes,7,opt,name=sig,proto3" json:"sig,omitempty"`                               // 64-byte Ed25519 signature
	Flags         uint32                 `protobuf:"varint,8,opt,name=flags,proto3" json:"flags,omitempty"`                          // Event flags
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_protos_eventstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Event) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *Event) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Event) GetKind() uint32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *Event) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Event) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Event) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *Event) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

// Tag represents a tag in an event
type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_protos_eventstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{1}
}

func (x *Tag) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// QueryFilter for filtering events
type QueryFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kinds         []uint32               `protobuf:"varint,1,rep,packed,name=kinds,proto3" json:"kinds,omitempty"`                                                                 // Event kinds to filter
	Authors       [][]byte               `protobuf:"bytes,2,rep,name=authors,proto3" json:"authors,omitempty"`                                                                     // Author pubkeys to filter
	Ids           [][]byte               `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`                                                                             // Event IDs to filter
	Since         uint32                 `protobuf:"varint,4,opt,name=since,proto3" json:"since,omitempty"`                                                                        // Minimum timestamp
	Until         uint32                 `protobuf:"varint,5,opt,name=until,proto3" json:"until,omitempty"`                                                                        // Maximum timestamp
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`                                                                        // Maximum results to return
	Tags          map[string]*TagFilter  `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Tag filters
	Search        string                 `protobuf:"bytes,8,opt,name=search,proto3" json:"search,omitempty"`                                                                       // Full-text search
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFilter) Reset() {
	*x = QueryFilter{}
	mi := &file_protos_eventstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFilter) ProtoMessage() {}

func (x *QueryFilter) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFilter.ProtoReflect.Descriptor instead.
func (*QueryFilter) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{2}
}

func (x *QueryFilter) GetKinds() []uint32 {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *QueryFilter) GetAuthors() [][]byte {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *QueryFilter) GetIds() [][]byte {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *QueryFilter) GetSince() uint32 {
	if x != nil {
		return x.Since
	}
	return 0
}

func (x *QueryFilter) GetUntil() uint32 {
	if x != nil {
		return x.Until
	}
	return 0
}

func (x *QueryFilter) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryFilter) GetTags() map[string]*TagFilter {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *QueryFilter) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

// TagFilter for tag-based filtering
type TagFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagFilter) Reset() {
	*x = TagFilter{}
	mi := &file_protos_eventstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagFilter) ProtoMessage() {}

func (x *TagFilter) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagFilter.ProtoReflect.Descriptor instead.
func (*TagFilter) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{3}
}

func (x *TagFilter) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// RecordLocation identifies where an event is stored
type RecordLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentId     uint32                 `protobuf:"varint,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordLocation) Reset() {
	*x = RecordLocation{}
	mi := &file_protos_eventstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordLocation) ProtoMessage() {}

func (x *RecordLocation) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordLocation.ProtoReflect.Descriptor instead.
func (*RecordLocation) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{4}
}

func (x *RecordLocation) GetSegmentId() uint32 {
	if x != nil {
		return x.SegmentId
	}
	return 0
}

func (x *RecordLocation) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// WriteEventRequest
type WriteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Event         *Event                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteEventRequest) Reset() {
	*x = WriteEventRequest{}
	mi := &file_protos_eventstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteEventRequest) ProtoMessage() {}

func (x *WriteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteEventRequest.ProtoReflect.Descriptor instead.
func (*WriteEventRequest) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{5}
}

func (x *WriteEventRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *WriteEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

// WriteEventResponse
type WriteEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*WriteEventResponse_Location
	//	*WriteEventResponse_Error
	Result        isWriteEventResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteEventResponse) Reset() {
	*x = WriteEventResponse{}
	mi := &file_protos_eventstore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteEventResponse) ProtoMessage() {}

func (x *WriteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteEventResponse.ProtoReflect.Descriptor instead.
func (*WriteEventResponse) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{6}
}

func (x *WriteEventResponse) GetResult() isWriteEventResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *WriteEventResponse) GetLocation() *RecordLocation {
	if x != nil {
		if x, ok := x.Result.(*WriteEventResponse_Location); ok {
			return x.Location
		}
	}
	return nil
}

func (x *WriteEventResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Result.(*WriteEventResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isWriteEventResponse_Result interface {
	isWriteEventResponse_Result()
}

type WriteEventResponse_Location struct {
	Location *RecordLocation `protobuf:"bytes,1,opt,name=location,proto3,oneof"`
}

type WriteEventResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*WriteEventResponse_Location) isWriteEventResponse_Result() {}

func (*WriteEventResponse_Error) isWriteEventResponse_Result() {}

// WriteEventsRequest
type WriteEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Events        []*Event               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteEventsRequest) Reset() {
	*x = WriteEventsRequest{}
	mi := &file_protos_eventstore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteEventsRequest) ProtoMessage() {}

func (x *WriteEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteEventsRequest.ProtoReflect.Descriptor instead.
func (*WriteEventsRequest) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{7}
}

func (x *WriteEventsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *WriteEventsRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// WriteEventsResponse
type WriteEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*WriteEventsResponse_Success
	//	*WriteEventsResponse_Error
	Result        isWriteEventsResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteEventsResponse) Reset() {
	*x = WriteEventsResponse{}
	mi := &file_protos_eventstore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteEventsResponse) ProtoMessage() {}

func (x *WriteEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteEventsResponse.ProtoReflect.Descriptor instead.
func (*WriteEventsResponse) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{8}
}

func (x *WriteEventsResponse) GetResult() isWriteEventsResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *WriteEventsResponse) GetSuccess() *WriteEventsResult {
	if x != nil {
		if x, ok := x.Result.(*WriteEventsResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *WriteEventsResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Result.(*WriteEventsResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isWriteEventsResponse_Result interface {
	isWriteEventsResponse_Result()
}

type WriteEventsResponse_Success struct {
	Success *WriteEventsResult `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type WriteEventsResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*WriteEventsResponse_Success) isWriteEventsResponse_Result() {}

func (*WriteEventsResponse_Error) isWriteEventsResponse_Result() {}

type WriteEventsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*RecordLocation      `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteEventsResult) Reset() {
	*x = WriteEventsResult{}
	mi := &file_protos_eventstore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteEventsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteEventsResult) ProtoMessage() {}

func (x *WriteEventsResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteEventsResult.ProtoReflect.Descriptor instead.
func (*WriteEventsResult) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{9}
}

func (x *WriteEventsResult) GetLocations() []*RecordLocation {
	if x != nil {
		return x.Locations
	}
	return nil
}

// GetEventRequest
type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	EventId       []byte                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_protos_eventstore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{10}
}

func (x *GetEventRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GetEventRequest) GetEventId() []byte {
	if x != nil {
		return x.EventId
	}
	return nil
}

// GetEventResponse
type GetEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetEventResponse_Event
	//	*GetEventResponse_Error
	Result        isGetEventResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventResponse) Reset() {
	*x = GetEventResponse{}
	mi := &file_protos_eventstore_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventResponse) ProtoMessage() {}

func (x *GetEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventResponse.ProtoReflect.Descriptor instead.
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{11}
}

func (x *GetEventResponse) GetResult() isGetEventResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetEventResponse) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Result.(*GetEventResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *GetEventResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Result.(*GetEventResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetEventResponse_Result interface {
	isGetEventResponse_Result()
}

type GetEventResponse_Event struct {
	Event *Event `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type GetEventResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetEventResponse_Event) isGetEventResponse_Result() {}

func (*GetEventResponse_Error) isGetEventResponse_Result() {}

// DeleteEventRequest
type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	EventId       []byte                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_protos_eventstore_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteEventRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *DeleteEventRequest) GetEventId() []byte {
	if x != nil {
		return x.EventId
	}
	return nil
}

// DeleteEventResponse
type DeleteEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*DeleteEventResponse_Success
	//	*DeleteEventResponse_Error
	Result        isDeleteEventResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_protos_eventstore_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteEventResponse) GetResult() isDeleteEventResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *DeleteEventResponse) GetSuccess() *DeleteEventResult {
	if x != nil {
		if x, ok := x.Result.(*DeleteEventResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *DeleteEventResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Result.(*DeleteEventResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isDeleteEventResponse_Result interface {
	isDeleteEventResponse_Result()
}

type DeleteEventResponse_Success struct {
	Success *DeleteEventResult `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type DeleteEventResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*DeleteEventResponse_Success) isDeleteEventResponse_Result() {}

func (*DeleteEventResponse_Error) isDeleteEventResponse_Result() {}

type DeleteEventResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResult) Reset() {
	*x = DeleteEventResult{}
	mi := &file_protos_eventstore_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResult) ProtoMessage() {}

func (x *DeleteEventResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResult.ProtoReflect.Descriptor instead.
func (*DeleteEventResult) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteEventResult) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// DeleteEventsRequest
type DeleteEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	EventIds      [][]byte               `protobuf:"bytes,2,rep,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventsRequest) Reset() {
	*x = DeleteEventsRequest{}
	mi := &file_protos_eventstore_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventsRequest) ProtoMessage() {}

func (x *DeleteEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventsRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventsRequest) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteEventsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *DeleteEventsRequest) GetEventIds() [][]byte {
	if x != nil {
		return x.EventIds
	}
	return nil
}

// DeleteEventsResponse
type DeleteEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*DeleteEventsResponse_Success
	//	*DeleteEventsResponse_Error
	Result        isDeleteEventsResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventsResponse) Reset() {
	*x = DeleteEventsResponse{}
	mi := &file_protos_eventstore_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventsResponse) ProtoMessage() {}

func (x *DeleteEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventsResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventsResponse) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteEventsResponse) GetResult() isDeleteEventsResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *DeleteEventsResponse) GetSuccess() *DeleteEventsResult {
	if x != nil {
		if x, ok := x.Result.(*DeleteEventsResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *DeleteEventsResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Result.(*DeleteEventsResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isDeleteEventsResponse_Result interface {
	isDeleteEventsResponse_Result()
}

type DeleteEventsResponse_Success struct {
	Success *DeleteEventsResult `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type DeleteEventsResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*DeleteEventsResponse_Success) isDeleteEventsResponse_Result() {}

func (*DeleteEventsResponse_Error) isDeleteEventsResponse_Result() {}

type DeleteEventsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventsResult) Reset() {
	*x = DeleteEventsResult{}
	mi := &file_protos_eventstore_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventsResult) ProtoMessage() {}

func (x *DeleteEventsResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventsResult.ProtoReflect.Descriptor instead.
func (*DeleteEventsResult) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteEventsResult) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

// QueryRequest
type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Filter        *QueryFilter           `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_protos_eventstore_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{18}
}

func (x *QueryRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *QueryRequest) GetFilter() *QueryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// QueryResponse (streamed)
type QueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*QueryResponse_Event
	//	*QueryResponse_Error
	Result        isQueryResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_protos_eventstore_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{19}
}

func (x *QueryResponse) GetResult() isQueryResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *QueryResponse) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Result.(*QueryResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *QueryResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Result.(*QueryResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isQueryResponse_Result interface {
	isQueryResponse_Result()
}

type QueryResponse_Event struct {
	Event *Event `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type QueryResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*QueryResponse_Event) isQueryResponse_Result() {}

func (*QueryResponse_Error) isQueryResponse_Result() {}

// QueryAllRequest
type QueryAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Filter        *QueryFilter           `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAllRequest) Reset() {
	*x = QueryAllRequest{}
	mi := &file_protos_eventstore_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAllRequest) ProtoMessage() {}

func (x *QueryAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAllRequest.ProtoReflect.Descriptor instead.
func (*QueryAllRequest) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{20}
}

func (x *QueryAllRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *QueryAllRequest) GetFilter() *QueryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// QueryAllResponse
type QueryAllResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*QueryAllResponse_Success
	//	*QueryAllResponse_Error
	Result        isQueryAllResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAllResponse) Reset() {
	*x = QueryAllResponse{}
	mi := &file_protos_eventstore_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAllResponse) ProtoMessage() {}

func (x *QueryAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAllResponse.ProtoReflect.Descriptor instead.
func (*QueryAllResponse) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{21}
}

func (x *QueryAllResponse) GetResult() isQueryAllResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *QueryAllResponse) GetSuccess() *QueryAllResult {
	if x != nil {
		if x, ok := x.Result.(*QueryAllResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *QueryAllResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Result.(*QueryAllResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isQueryAllResponse_Result interface {
	isQueryAllResponse_Result()
}

type QueryAllResponse_Success struct {
	Success *QueryAllResult `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type QueryAllResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*QueryAllResponse_Success) isQueryAllResponse_Result() {}

func (*QueryAllResponse_Error) isQueryAllResponse_Result() {}

type QueryAllResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryAllResult) Reset() {
	*x = QueryAllResult{}
	mi := &file_protos_eventstore_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryAllResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAllResult) ProtoMessage() {}

func (x *QueryAllResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAllResult.ProtoReflect.Descriptor instead.
func (*QueryAllResult) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{22}
}

func (x *QueryAllResult) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// QueryCountRequest
type QueryCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Filter        *QueryFilter           `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCountRequest) Reset() {
	*x = QueryCountRequest{}
	mi := &file_protos_eventstore_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCountRequest) ProtoMessage() {}

func (x *QueryCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCountRequest.ProtoReflect.Descriptor instead.
func (*QueryCountRequest) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{23}
}

func (x *QueryCountRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *QueryCountRequest) GetFilter() *QueryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// QueryCountResponse
type QueryCountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*QueryCountResponse_Success
	//	*QueryCountResponse_Error
	Result        isQueryCountResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCountResponse) Reset() {
	*x = QueryCountResponse{}
	mi := &file_protos_eventstore_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCountResponse) ProtoMessage() {}

func (x *QueryCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCountResponse.ProtoReflect.Descriptor instead.
func (*QueryCountResponse) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{24}
}

func (x *QueryCountResponse) GetResult() isQueryCountResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *QueryCountResponse) GetSuccess() *QueryCountResult {
	if x != nil {
		if x, ok := x.Result.(*QueryCountResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *QueryCountResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Result.(*QueryCountResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isQueryCountResponse_Result interface {
	isQueryCountResponse_Result()
}

type QueryCountResponse_Success struct {
	Success *QueryCountResult `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type QueryCountResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*QueryCountResponse_Success) isQueryCountResponse_Result() {}

func (*QueryCountResponse_Error) isQueryCountResponse_Result() {}

type QueryCountResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCountResult) Reset() {
	*x = QueryCountResult{}
	mi := &file_protos_eventstore_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCountResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCountResult) ProtoMessage() {}

func (x *QueryCountResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCountResult.ProtoReflect.Descriptor instead.
func (*QueryCountResult) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{25}
}

func (x *QueryCountResult) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// StatsRequest
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_protos_eventstore_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{26}
}

func (x *StatsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// StatsResponse
type StatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*StatsResponse_Stats
	//	*StatsResponse_Error
	Result        isStatsResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_protos_eventstore_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{27}
}

func (x *StatsResponse) GetResult() isStatsResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *StatsResponse) GetStats() *StorageStats {
	if x != nil {
		if x, ok := x.Result.(*StatsResponse_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

func (x *StatsResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Result.(*StatsResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isStatsResponse_Result interface {
	isStatsResponse_Result()
}

type StatsResponse_Stats struct {
	Stats *StorageStats `protobuf:"bytes,1,opt,name=stats,proto3,oneof"`
}

type StatsResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*StatsResponse_Stats) isStatsResponse_Result() {}

func (*StatsResponse_Error) isStatsResponse_Result() {}

type StorageStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventCount    uint64                 `protobuf:"varint,1,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	TotalSize     uint64                 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	SegmentCount  uint64                 `protobuf:"varint,3,opt,name=segment_count,json=segmentCount,proto3" json:"segment_count,omitempty"`
	IndexSize     uint64                 `protobuf:"varint,4,opt,name=index_size,json=indexSize,proto3" json:"index_size,omitempty"`
	WalSize       uint64                 `protobuf:"varint,5,opt,name=wal_size,json=walSize,proto3" json:"wal_size,omitempty"`
	CustomStats   map[string]int64       `protobuf:"bytes,6,rep,name=custom_stats,json=customStats,proto3" json:"custom_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageStats) Reset() {
	*x = StorageStats{}
	mi := &file_protos_eventstore_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageStats) ProtoMessage() {}

func (x *StorageStats) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageStats.ProtoReflect.Descriptor instead.
func (*StorageStats) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{28}
}

func (x *StorageStats) GetEventCount() uint64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *StorageStats) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *StorageStats) GetSegmentCount() uint64 {
	if x != nil {
		return x.SegmentCount
	}
	return 0
}

func (x *StorageStats) GetIndexSize() uint64 {
	if x != nil {
		return x.IndexSize
	}
	return 0
}

func (x *StorageStats) GetWalSize() uint64 {
	if x != nil {
		return x.WalSize
	}
	return 0
}

func (x *StorageStats) GetCustomStats() map[string]int64 {
	if x != nil {
		return x.CustomStats
	}
	return nil
}

// FlushRequest
type FlushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushRequest) Reset() {
	*x = FlushRequest{}
	mi := &file_protos_eventstore_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushRequest) ProtoMessage() {}

func (x *FlushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushRequest.ProtoReflect.Descriptor instead.
func (*FlushRequest) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{29}
}

func (x *FlushRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// FlushResponse
type FlushResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*FlushResponse_Success
	//	*FlushResponse_Error
	Result        isFlushResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushResponse) Reset() {
	*x = FlushResponse{}
	mi := &file_protos_eventstore_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushResponse) ProtoMessage() {}

func (x *FlushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushResponse.ProtoReflect.Descriptor instead.
func (*FlushResponse) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{30}
}

func (x *FlushResponse) GetResult() isFlushResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *FlushResponse) GetSuccess() *FlushResult {
	if x != nil {
		if x, ok := x.Result.(*FlushResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *FlushResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Result.(*FlushResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isFlushResponse_Result interface {
	isFlushResponse_Result()
}

type FlushResponse_Success struct {
	Success *FlushResult `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type FlushResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*FlushResponse_Success) isFlushResponse_Result() {}

func (*FlushResponse_Error) isFlushResponse_Result() {}

type FlushResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flushed       bool                   `protobuf:"varint,1,opt,name=flushed,proto3" json:"flushed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushResult) Reset() {
	*x = FlushResult{}
	mi := &file_protos_eventstore_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushResult) ProtoMessage() {}

func (x *FlushResult) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushResult.ProtoReflect.Descriptor instead.
func (*FlushResult) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{31}
}

func (x *FlushResult) GetFlushed() bool {
	if x != nil {
		return x.Flushed
	}
	return false
}

// HealthCheckRequest
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_protos_eventstore_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{32}
}

func (x *HealthCheckRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// HealthCheckResponse
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_protos_eventstore_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{33}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ErrorResponse for error handling
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`       // Error code (e.g., "ErrEventNotFound")
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Human-readable error message
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"` // Additional error details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_protos_eventstore_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_eventstore_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_protos_eventstore_proto_rawDescGZIP(), []int{34}
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_protos_eventstore_proto protoreflect.FileDescriptor

const file_protos_eventstore_proto_rawDesc = "" +
	"\n" +
	"\x17protos/eventstore.proto\x12\n" +
	"eventstore\"\xc9\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x16\n" +
	"\x06pubkey\x18\x02 \x01(\fR\x06pubkey\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\rR\tcreatedAt\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\rR\x04kind\x12#\n" +
	"\x04tags\x18\x05 \x03(\v2\x0f.eventstore.TagR\x04tags\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x10\n" +
	"\x03sig\x18\a \x01(\fR\x03sig\x12\x14\n" +
	"\x05flags\x18\b \x01(\rR\x05flags\"\x1d\n" +
	"\x03Tag\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xb0\x02\n" +
	"\vQueryFilter\x12\x14\n" +
	"\x05kinds\x18\x01 \x03(\rR\x05kinds\x12\x18\n" +
	"\aauthors\x18\x02 \x03(\fR\aauthors\x12\x10\n" +
	"\x03ids\x18\x03 \x03(\fR\x03ids\x12\x14\n" +
	"\x05since\x18\x04 \x01(\rR\x05since\x12\x14\n" +
	"\x05until\x18\x05 \x01(\rR\x05until\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x125\n" +
	"\x04tags\x18\a \x03(\v2!.eventstore.QueryFilter.TagsEntryR\x04tags\x12\x16\n" +
	"\x06search\x18\b \x01(\tR\x06search\x1aN\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.eventstore.TagFilterR\x05value:\x028\x01\"#\n" +
	"\tTagFilter\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"G\n" +
	"\x0eRecordLocation\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\rR\tsegmentId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\"U\n" +
	"\x11WriteEventRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12'\n" +
	"\x05event\x18\x02 \x01(\v2\x11.eventstore.EventR\x05event\"\x8b\x01\n" +
	"\x12WriteEventResponse\x128\n" +
	"\blocation\x18\x01 \x01(\v2\x1a.eventstore.RecordLocationH\x00R\blocation\x121\n" +
	"\x05error\x18\x02 \x01(\v2\x19.eventstore.ErrorResponseH\x00R\x05errorB\b\n" +
	"\x06result\"X\n" +
	"\x12WriteEventsRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12)\n" +
	"\x06events\x18\x02 \x03(\v2\x11.eventstore.EventR\x06events\"\x8d\x01\n" +
	"\x13WriteEventsResponse\x129\n" +
	"\asuccess\x18\x01 \x01(\v2\x1d.eventstore.WriteEventsResultH\x00R\asuccess\x121\n" +
	"\x05error\x18\x02 \x01(\v2\x19.eventstore.ErrorResponseH\x00R\x05errorB\b\n" +
	"\x06result\"M\n" +
	"\x11WriteEventsResult\x128\n" +
	"\tlocations\x18\x01 \x03(\v2\x1a.eventstore.RecordLocationR\tlocations\"E\n" +
	"\x0fGetEventRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\fR\aeventId\"z\n" +
	"\x10GetEventResponse\x12)\n" +
	"\x05event\x18\x01 \x01(\v2\x11.eventstore.EventH\x00R\x05event\x121\n" +
	"\x05error\x18\x02 \x01(\v2\x19.eventstore.ErrorResponseH\x00R\x05errorB\b\n" +
	"\x06result\"H\n" +
	"\x12DeleteEventRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\fR\aeventId\"\x8d\x01\n" +
	"\x13DeleteEventResponse\x129\n" +
	"\asuccess\x18\x01 \x01(\v2\x1d.eventstore.DeleteEventResultH\x00R\asuccess\x121\n" +
	"\x05error\x18\x02 \x01(\v2\x19.eventstore.ErrorResponseH\x00R\x05errorB\b\n" +
	"\x06result\"-\n" +
	"\x11DeleteEventResult\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"K\n" +
	"\x13DeleteEventsRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1b\n" +
	"\tevent_ids\x18\x02 \x03(\fR\beventIds\"\x8f\x01\n" +
	"\x14DeleteEventsResponse\x12:\n" +
	"\asuccess\x18\x01 \x01(\v2\x1e.eventstore.DeleteEventsResultH\x00R\asuccess\x121\n" +
	"\x05error\x18\x02 \x01(\v2\x19.eventstore.ErrorResponseH\x00R\x05errorB\b\n" +
	"\x06result\"9\n" +
	"\x12DeleteEventsResult\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount\"X\n" +
	"\fQueryRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12/\n" +
	"\x06filter\x18\x02 \x01(\v2\x17.eventstore.QueryFilterR\x06filter\"w\n" +
	"\rQueryResponse\x12)\n" +
	"\x05event\x18\x01 \x01(\v2\x11.eventstore.EventH\x00R\x05event\x121\n" +
	"\x05error\x18\x02 \x01(\v2\x19.eventstore.ErrorResponseH\x00R\x05errorB\b\n" +
	"\x06result\"[\n" +
	"\x0fQueryAllRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12/\n" +
	"\x06filter\x18\x02 \x01(\v2\x17.eventstore.QueryFilterR\x06filter\"\x87\x01\n" +
	"\x10QueryAllResponse\x126\n" +
	"\asuccess\x18\x01 \x01(\v2\x1a.eventstore.QueryAllResultH\x00R\asuccess\x121\n" +
	"\x05error\x18\x02 \x01(\v2\x19.eventstore.ErrorResponseH\x00R\x05errorB\b\n" +
	"\x06result\";\n" +
	"\x0eQueryAllResult\x12)\n" +
	"\x06events\x18\x01 \x03(\v2\x11.eventstore.EventR\x06events\"]\n" +
	"\x11QueryCountRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12/\n" +
	"\x06filter\x18\x02 \x01(\v2\x17.eventstore.QueryFilterR\x06filter\"\x8b\x01\n" +
	"\x12QueryCountResponse\x128\n" +
	"\asuccess\x18\x01 \x01(\v2\x1c.eventstore.QueryCountResultH\x00R\asuccess\x121\n" +
	"\x05error\x18\x02 \x01(\v2\x19.eventstore.ErrorResponseH\x00R\x05errorB\b\n" +
	"\x06result\"(\n" +
	"\x10QueryCountResult\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"'\n" +
	"\fStatsRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"~\n" +
	"\rStatsResponse\x120\n" +
	"\x05stats\x18\x01 \x01(\v2\x18.eventstore.StorageStatsH\x00R\x05stats\x121\n" +
	"\x05error\x18\x02 \x01(\v2\x19.eventstore.ErrorResponseH\x00R\x05errorB\b\n" +
	"\x06result\"\xbb\x02\n" +
	"\fStorageStats\x12\x1f\n" +
	"\vevent_count\x18\x01 \x01(\x04R\n" +
	"eventCount\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x04R\ttotalSize\x12#\n" +
	"\rsegment_count\x18\x03 \x01(\x04R\fsegmentCount\x12\x1d\n" +
	"\n" +
	"index_size\x18\x04 \x01(\x04R\tindexSize\x12\x19\n" +
	"\bwal_size\x18\x05 \x01(\x04R\awalSize\x12L\n" +
	"\fcustom_stats\x18\x06 \x03(\v2).eventstore.StorageStats.CustomStatsEntryR\vcustomStats\x1a>\n" +
	"\x10CustomStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"'\n" +
	"\fFlushRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"\x81\x01\n" +
	"\rFlushResponse\x123\n" +
	"\asuccess\x18\x01 \x01(\v2\x17.eventstore.FlushResultH\x00R\asuccess\x121\n" +
	"\x05error\x18\x02 \x01(\v2\x19.eventstore.ErrorResponseH\x00R\x05errorB\b\n" +
	"\x06result\"'\n" +
	"\vFlushResult\x12\x18\n" +
	"\aflushed\x18\x01 \x01(\bR\aflushed\"-\n" +
	"\x12HealthCheckRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"G\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"W\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails2\xb3\x06\n" +
	"\n" +
	"EventStore\x12K\n" +
	"\n" +
	"WriteEvent\x12\x1d.eventstore.WriteEventRequest\x1a\x1e.eventstore.WriteEventResponse\x12N\n" +
	"\vWriteEvents\x12\x1e.eventstore.WriteEventsRequest\x1a\x1f.eventstore.WriteEventsResponse\x12E\n" +
	"\bGetEvent\x12\x1b.eventstore.GetEventRequest\x1a\x1c.eventstore.GetEventResponse\x12N\n" +
	"\vDeleteEvent\x12\x1e.eventstore.DeleteEventRequest\x1a\x1f.eventstore.DeleteEventResponse\x12Q\n" +
	"\fDeleteEvents\x12\x1f.eventstore.DeleteEventsRequest\x1a .eventstore.DeleteEventsResponse\x12>\n" +
	"\x05Query\x12\x18.eventstore.QueryRequest\x1a\x19.eventstore.QueryResponse0\x01\x12E\n" +
	"\bQueryAll\x12\x1b.eventstore.QueryAllRequest\x1a\x1c.eventstore.QueryAllResponse\x12K\n" +
	"\n" +
	"QueryCount\x12\x1d.eventstore.QueryCountRequest\x1a\x1e.eventstore.QueryCountResponse\x12<\n" +
	"\x05Stats\x12\x18.eventstore.StatsRequest\x1a\x19.eventstore.StatsResponse\x12<\n" +
	"\x05Flush\x12\x18.eventstore.FlushRequest\x1a\x19.eventstore.FlushResponse\x12N\n" +
	"\vHealthCheck\x12\x1e.eventstore.HealthCheckRequest\x1a\x1f.eventstore.HealthCheckResponseB%Z#nostr_event_store/protos/eventstoreb\x06proto3"

var (
	file_protos_eventstore_proto_rawDescOnce sync.Once
	file_protos_eventstore_proto_rawDescData []byte
)

func file_protos_eventstore_proto_rawDescGZIP() []byte {
	file_protos_eventstore_proto_rawDescOnce.Do(func() {
		file_protos_eventstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_eventstore_proto_rawDesc), len(file_protos_eventstore_proto_rawDesc)))
	})
	return file_protos_eventstore_proto_rawDescData
}

var file_protos_eventstore_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_protos_eventstore_proto_goTypes = []any{
	(*Event)(nil),                // 0: eventstore.Event
	(*Tag)(nil),                  // 1: eventstore.Tag
	(*QueryFilter)(nil),          // 2: eventstore.QueryFilter
	(*TagFilter)(nil),            // 3: eventstore.TagFilter
	(*RecordLocation)(nil),       // 4: eventstore.RecordLocation
	(*WriteEventRequest)(nil),    // 5: eventstore.WriteEventRequest
	(*WriteEventResponse)(nil),   // 6: eventstore.WriteEventResponse
	(*WriteEventsRequest)(nil),   // 7: eventstore.WriteEventsRequest
	(*WriteEventsResponse)(nil),  // 8: eventstore.WriteEventsResponse
	(*WriteEventsResult)(nil),    // 9: eventstore.WriteEventsResult
	(*GetEventRequest)(nil),      // 10: eventstore.GetEventRequest
	(*GetEventResponse)(nil),     // 11: eventstore.GetEventResponse
	(*DeleteEventRequest)(nil),   // 12: eventstore.DeleteEventRequest
	(*DeleteEventResponse)(nil),  // 13: eventstore.DeleteEventResponse
	(*DeleteEventResult)(nil),    // 14: eventstore.DeleteEventResult
	(*DeleteEventsRequest)(nil),  // 15: eventstore.DeleteEventsRequest
	(*DeleteEventsResponse)(nil), // 16: eventstore.DeleteEventsResponse
	(*DeleteEventsResult)(nil),   // 17: eventstore.DeleteEventsResult
	(*QueryRequest)(nil),         // 18: eventstore.QueryRequest
	(*QueryResponse)(nil),        // 19: eventstore.QueryResponse
	(*QueryAllRequest)(nil),      // 20: eventstore.QueryAllRequest
	(*QueryAllResponse)(nil),     // 21: eventstore.QueryAllResponse
	(*QueryAllResult)(nil),       // 22: eventstore.QueryAllResult
	(*QueryCountRequest)(nil),    // 23: eventstore.QueryCountRequest
	(*QueryCountResponse)(nil),   // 24: eventstore.QueryCountResponse
	(*QueryCountResult)(nil),     // 25: eventstore.QueryCountResult
	(*StatsRequest)(nil),         // 26: eventstore.StatsRequest
	(*StatsResponse)(nil),        // 27: eventstore.StatsResponse
	(*StorageStats)(nil),         // 28: eventstore.StorageStats
	(*FlushRequest)(nil),         // 29: eventstore.FlushRequest
	(*FlushResponse)(nil),        // 30: eventstore.FlushResponse
	(*FlushResult)(nil),          // 31: eventstore.FlushResult
	(*HealthCheckRequest)(nil),   // 32: eventstore.HealthCheckRequest
	(*HealthCheckResponse)(nil),  // 33: eventstore.HealthCheckResponse
	(*ErrorResponse)(nil),        // 34: eventstore.ErrorResponse
	nil,                          // 35: eventstore.QueryFilter.TagsEntry
	nil,                          // 36: eventstore.StorageStats.CustomStatsEntry
}
var file_protos_eventstore_proto_depIdxs = []int32{
	1,  // 0: eventstore.Event.tags:type_name -> eventstore.Tag
	35, // 1: eventstore.QueryFilter.tags:type_name -> eventstore.QueryFilter.TagsEntry
	0,  // 2: eventstore.WriteEventRequest.event:type_name -> eventstore.Event
	4,  // 3: eventstore.WriteEventResponse.location:type_name -> eventstore.RecordLocation
	34, // 4: eventstore.WriteEventResponse.error:type_name -> eventstore.ErrorResponse
	0,  // 5: eventstore.WriteEventsRequest.events:type_name -> eventstore.Event
	9,  // 6: eventstore.WriteEventsResponse.success:type_name -> eventstore.WriteEventsResult
	34, // 7: eventstore.WriteEventsResponse.error:type_name -> eventstore.ErrorResponse
	4,  // 8: eventstore.WriteEventsResult.locations:type_name -> eventstore.RecordLocation
	0,  // 9: eventstore.GetEventResponse.event:type_name -> eventstore.Event
	34, // 10: eventstore.GetEventResponse.error:type_name -> eventstore.ErrorResponse
	14, // 11: eventstore.DeleteEventResponse.success:type_name -> eventstore.DeleteEventResult
	34, // 12: eventstore.DeleteEventResponse.error:type_name -> eventstore.ErrorResponse
	17, // 13: eventstore.DeleteEventsResponse.success:type_name -> eventstore.DeleteEventsResult
	34, // 14: eventstore.DeleteEventsResponse.error:type_name -> eventstore.ErrorResponse
	2,  // 15: eventstore.QueryRequest.filter:type_name -> eventstore.QueryFilter
	0,  // 16: eventstore.QueryResponse.event:type_name -> eventstore.Event
	34, // 17: eventstore.QueryResponse.error:type_name -> eventstore.ErrorResponse
	2,  // 18: eventstore.QueryAllRequest.filter:type_name -> eventstore.QueryFilter
	22, // 19: eventstore.QueryAllResponse.success:type_name -> eventstore.QueryAllResult
	34, // 20: eventstore.QueryAllResponse.error:type_name -> eventstore.ErrorResponse
	0,  // 21: eventstore.QueryAllResult.events:type_name -> eventstore.Event
	2,  // 22: eventstore.QueryCountRequest.filter:type_name -> eventstore.QueryFilter
	25, // 23: eventstore.QueryCountResponse.success:type_name -> eventstore.QueryCountResult
	34, // 24: eventstore.QueryCountResponse.error:type_name -> eventstore.ErrorResponse
	28, // 25: eventstore.StatsResponse.stats:type_name -> eventstore.StorageStats
	34, // 26: eventstore.StatsResponse.error:type_name -> eventstore.ErrorResponse
	36, // 27: eventstore.StorageStats.custom_stats:type_name -> eventstore.StorageStats.CustomStatsEntry
	31, // 28: eventstore.FlushResponse.success:type_name -> eventstore.FlushResult
	34, // 29: eventstore.FlushResponse.error:type_name -> eventstore.ErrorResponse
	3,  // 30: eventstore.QueryFilter.TagsEntry.value:type_name -> eventstore.TagFilter
	5,  // 31: eventstore.EventStore.WriteEvent:input_type -> eventstore.WriteEventRequest
	7,  // 32: eventstore.EventStore.WriteEvents:input_type -> eventstore.WriteEventsRequest
	10, // 33: eventstore.EventStore.GetEvent:input_type -> eventstore.GetEventRequest
	12, // 34: eventstore.EventStore.DeleteEvent:input_type -> eventstore.DeleteEventRequest
	15, // 35: eventstore.EventStore.DeleteEvents:input_type -> eventstore.DeleteEventsRequest
	18, // 36: eventstore.EventStore.Query:input_type -> eventstore.QueryRequest
	20, // 37: eventstore.EventStore.QueryAll:input_type -> eventstore.QueryAllRequest
	23, // 38: eventstore.EventStore.QueryCount:input_type -> eventstore.QueryCountRequest
	26, // 39: eventstore.EventStore.Stats:input_type -> eventstore.StatsRequest
	29, // 40: eventstore.EventStore.Flush:input_type -> eventstore.FlushRequest
	32, // 41: eventstore.EventStore.HealthCheck:input_type -> eventstore.HealthCheckRequest
	6,  // 42: eventstore.EventStore.WriteEvent:output_type -> eventstore.WriteEventResponse
	8,  // 43: eventstore.EventStore.WriteEvents:output_type -> eventstore.WriteEventsResponse
	11, // 44: eventstore.EventStore.GetEvent:output_type -> eventstore.GetEventResponse
	13, // 45: eventstore.EventStore.DeleteEvent:output_type -> eventstore.DeleteEventResponse
	16, // 46: eventstore.EventStore.DeleteEvents:output_type -> eventstore.DeleteEventsResponse
	19, // 47: eventstore.EventStore.Query:output_type -> eventstore.QueryResponse
	21, // 48: eventstore.EventStore.QueryAll:output_type -> eventstore.QueryAllResponse
	24, // 49: eventstore.EventStore.QueryCount:output_type -> eventstore.QueryCountResponse
	27, // 50: eventstore.EventStore.Stats:output_type -> eventstore.StatsResponse
	30, // 51: eventstore.EventStore.Flush:output_type -> eventstore.FlushResponse
	33, // 52: eventstore.EventStore.HealthCheck:output_type -> eventstore.HealthCheckResponse
	42, // [42:53] is the sub-list for method output_type
	31, // [31:42] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_protos_eventstore_proto_init() }
func file_protos_eventstore_proto_init() {
	if File_protos_eventstore_proto != nil {
		return
	}
	file_protos_eventstore_proto_msgTypes[6].OneofWrappers = []any{
		(*WriteEventResponse_Location)(nil),
		(*WriteEventResponse_Error)(nil),
	}
	file_protos_eventstore_proto_msgTypes[8].OneofWrappers = []any{
		(*WriteEventsResponse_Success)(nil),
		(*WriteEventsResponse_Error)(nil),
	}
	file_protos_eventstore_proto_msgTypes[11].OneofWrappers = []any{
		(*GetEventResponse_Event)(nil),
		(*GetEventResponse_Error)(nil),
	}
	file_protos_eventstore_proto_msgTypes[13].OneofWrappers = []any{
		(*DeleteEventResponse_Success)(nil),
		(*DeleteEventResponse_Error)(nil),
	}
	file_protos_eventstore_proto_msgTypes[16].OneofWrappers = []any{
		(*DeleteEventsResponse_Success)(nil),
		(*DeleteEventsResponse_Error)(nil),
	}
	file_protos_eventstore_proto_msgTypes[19].OneofWrappers = []any{
		(*QueryResponse_Event)(nil),
		(*QueryResponse_Error)(nil),
	}
	file_protos_eventstore_proto_msgTypes[21].OneofWrappers = []any{
		(*QueryAllResponse_Success)(nil),
		(*QueryAllResponse_Error)(nil),
	}
	file_protos_eventstore_proto_msgTypes[24].OneofWrappers = []any{
		(*QueryCountResponse_Success)(nil),
		(*QueryCountResponse_Error)(nil),
	}
	file_protos_eventstore_proto_msgTypes[27].OneofWrappers = []any{
		(*StatsResponse_Stats)(nil),
		(*StatsResponse_Error)(nil),
	}
	file_protos_eventstore_proto_msgTypes[30].OneofWrappers = []any{
		(*FlushResponse_Success)(nil),
		(*FlushResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_eventstore_proto_rawDesc), len(file_protos_eventstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_eventstore_proto_goTypes,
		DependencyIndexes: file_protos_eventstore_proto_depIdxs,
		MessageInfos:      file_protos_eventstore_proto_msgTypes,
	}.Build()
	File_protos_eventstore_proto = out.File
	file_protos_eventstore_proto_goTypes = nil
	file_protos_eventstore_proto_depIdxs = nil
}
